default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: <%= Rails.application.credentials.user[:name] %>
  password: <%= Rails.application.credentials.user[:pass] %>
development:
  <<: *default
  database: mini_twitter_development
test:
  <<: *default
  database: mini_twitter_test
production:
  <<: *default
  database: mini_twitter_production
